name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      run: cargo build --release
    - name: Fetch action
      id: pl
      uses: Rishabh510/Path-lister-action@master
      with:
        path: ".github/"
        type: ".exe"
