name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: swsh-event-dumper-${{ matrix.os }}
        path: |
          target/release/swsh_event_dumper.*
          target/release/swsh_event_dumper.*
          !target/release/*.d
